### PR TITLE
Add support for npm lint

### PR DESCRIPTION
**Pull request by birkholz**
If a project contains a `package.json`, Linty will run `npm install`, followed by `npm run lint`, and use the results of that script as the lint results.

This also restricts pycodestyle to only projects which contain a `requirements.txt` in the root of the project. Better project detection can come later.

### Warnings

Because this runs whatever the project has in its `lint` script, some pretty terrible things could happen. Some sort of project isolation should come eventually.

### CODE REVIEW

**Comment by jadengore** [comment]
@birkholz Keep in mind that this requires a user's project to have `npm run lint`. I know this is probably fine for @Zerocater since you guys probably follow this convention. Nevertheless, for people who use Gulp for their tooling and want to use Linty, you should add some documentation that says you need a `lint` command in your `package.json`.

**Comment by birkholz** [comment]
At the moment, python and JS are handled very differently:

**Python** projects are linted with a global version of pycodestyle, which can be configured with a `setup.cfg` file. But nothing is required to get linting immediately with pycodestyle.

**Javascript** requires the user to create a `package.json` file with a `lint` script, requiring the user to choose their own linter. Further, the linter has to return a non-zero status code for errors in order for Linty to register it as a failure.

I'd like to bring both paths closer to each other. Allow Python projects to override the linter, and allow JS apps to use a default linter without writing a lint script. This can be done with future iterations. For 1st pass, this is an acceptable solution.

**Comment by jadengore** [comment]
Yeah I understand that, but there's no documentation for this in the README. Was just suggesting you might want to add some for people using JS. 😄

**Comment by birkholz** [comment]
@jadengore Writing an change to the README now. ;)

**Comment by birkholz** [comment]
@jadengore [Tell me what you think](https://github.com/ZeroCater/linty/blob/d0b8a285212914f883afd1536af1da68415a5c5e/README.md)

**Comment by jadengore** [comment]
@birkholz 👏 👏 👏, prelimenary LGTM on your code even though I'm no Pythonista. 😆

**Pull request merged**
